# Generated by Django 5.1.4 on 2025-01-14 15:41

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BilanBiologique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateExamen', models.DateField(default=datetime.date.today)),
                ('resultatGlobal', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConsultationMedicale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premiere', models.BooleanField(default=True)),
                ('dateConsultation', models.DateField(default=datetime.date.today)),
                ('outilsConsultation', models.CharField(choices=[('Stéthoscope', 'Stéthoscope'), ('Tensiomètre', 'Tensiomètre'), ('Thermomètre', 'Tensiomètre')], default='Stéthoscope', max_length=50)),
                ('resume', models.CharField(max_length=500)),
                ('dateProchaineConsultation', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dpi_consultationmedicale',
            },
        ),
        migrations.CreateModel(
            name='DPI',
            fields=[
                ('numeroSecuriteSociale', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('dateDeNaissance', models.DateField(default=datetime.date.today)),
                ('adresse', models.TextField(default='')),
                ('telephone', models.DecimalField(decimal_places=0, max_digits=10)),
                ('mutuelle', models.CharField(max_length=30)),
                ('idMedecinTraitant', models.TextField(default='')),
                ('personneAcontacter', models.CharField(default=None, max_length=50)),
            ],
            options={
                'db_table': 'dpi_dpi',
            },
        ),
        migrations.CreateModel(
            name='Hopital',
            fields=[
                ('nom', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('nomMedicament', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('forme', models.CharField(choices=[('Orale', 'Orale'), ('Injectable', 'Injectable'), ('Dermique', 'Dermique')], default='Orale', max_length=20)),
                ('quantiteStock', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'dpi_medicament',
            },
        ),
        migrations.CreateModel(
            name='PieceJointe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='Attached-files/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'png', 'jpeg', 'jpg'])])),
            ],
            options={
                'db_table': 'dpi_piecejointe',
            },
        ),
        migrations.CreateModel(
            name='CompteAdministrateur',
            fields=[
                ('email', models.CharField(default=None, max_length=100, primary_key=True, serialize=False)),
                ('nomComplet', models.CharField(max_length=100)),
                ('motDePasse', models.CharField(max_length=255)),
                ('user', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Antecedent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeAntecedent', models.CharField(choices=[('Médical personnel', 'Médical personnel'), ('Familial', 'Familial'), ('Médicamenteux', 'Médicamenteux'), ('Social et environnemental', 'Social et environnemental'), ('Obstétrical et gynécologique', 'Obstétrical et gynécologique')], default='Médical personnel', max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('idConsultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DPI.consultationmedicale')),
            ],
            options={
                'db_table': 'dpi_antecedent',
            },
        ),
        migrations.CreateModel(
            name='ComptePatient',
            fields=[
                ('email', models.CharField(default=None, max_length=100, primary_key=True, serialize=False)),
                ('nomComplet', models.CharField(max_length=100)),
                ('motDePasse', models.CharField(max_length=255)),
                ('user', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('dossierPatient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DPI.dpi')),
            ],
            options={
                'db_table': 'dpi_comptepatient',
            },
        ),
        migrations.CreateModel(
            name='CompteRadiologue',
            fields=[
                ('email', models.CharField(default=None, max_length=100, primary_key=True, serialize=False)),
                ('nomComplet', models.CharField(max_length=100)),
                ('motDePasse', models.CharField(max_length=255)),
                ('user', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('idHopital', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='DPI.hopital')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComptePharmacien',
            fields=[
                ('email', models.CharField(default=None, max_length=100, primary_key=True, serialize=False)),
                ('nomComplet', models.CharField(max_length=100)),
                ('motDePasse', models.CharField(max_length=255)),
                ('user', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('idHopital', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='DPI.hopital')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComptePersonnelAdministratif',
            fields=[
                ('email', models.CharField(default=None, max_length=100, primary_key=True, serialize=False)),
                ('nomComplet', models.CharField(max_length=100)),
                ('motDePasse', models.CharField(max_length=255)),
                ('service', models.CharField(choices=[('Urgences', 'Urgences'), ('Réanimation', 'Réanimation'), ('Pédiatrie', 'Pédiatrie'), ('Cardiologie', 'Cardiologie'), ('Endocrinologie', 'Endocrinologie'), ('Dermatologie', 'Dermatologie'), ('Neurologie', 'Neurologie'), ('Obstétrique', 'Obstétrique'), ('Ostéologie', 'Ostéologie'), ('Ophtalmologie', 'Ophtalmologie'), ('ORL', 'ORL'), ('Gastro-entérologie', 'Gastro-entérologie'), ('Néphrologie', 'Néphrologie'), ('Orthopédie', 'Orthopédie'), ('Anesthésiologie', 'Anesthésiologie')], default='Urgences', max_length=30)),
                ('user', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('idHopital', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='DPI.hopital')),
            ],
            options={
                'db_table': 'dpi_personneladministratif',
            },
        ),
        migrations.CreateModel(
            name='CompteMedecin',
            fields=[
                ('nomComplet', models.CharField(max_length=100)),
                ('motDePasse', models.CharField(max_length=255)),
                ('email', models.CharField(default=None, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('specialite', models.CharField(choices=[('Chirurgien', 'Chirurgien'), ('Généraliste', 'Généraliste'), ('Pédiatre', 'Pédiatre'), ('Endocrinologue', 'Endocrinologue'), ('Cardiologue', 'Cardiologue'), ('Dermatologue', 'Dermatologue'), ('Neurologue', 'Neurologue'), ('Obstétricien', 'Obstétricien'), ('Ostéologue', 'Ostéologue'), ('Ophtalmologue', 'Ophtalmologue'), ('ORL', 'ORL'), ('Gastro-entérologue', 'Gastro-entérologue'), ('Néphrologue', 'Néphrologue'), ('Anesthésiste', 'Anesthésiste')], default='Généraliste', max_length=30)),
                ('user', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('idHopital', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='DPI.hopital')),
            ],
            options={
                'db_table': 'dpi_comptemedecin',
            },
        ),
        migrations.CreateModel(
            name='CompteLaborantin',
            fields=[
                ('email', models.CharField(default=None, max_length=100, primary_key=True, serialize=False)),
                ('nomComplet', models.CharField(max_length=100)),
                ('motDePasse', models.CharField(max_length=255)),
                ('user', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('idHopital', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='DPI.hopital')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompteInfirmier',
            fields=[
                ('email', models.CharField(default=None, max_length=100, primary_key=True, serialize=False)),
                ('nomComplet', models.CharField(max_length=100)),
                ('motDePasse', models.CharField(max_length=255)),
                ('specialiteInf', models.CharField(choices=[('de bloc opératoire', 'de bloc opératoire'), ('anesthésiste', 'anesthésiste'), ('puériculteur', 'puériculteur'), ('en pratique avancée', 'en pratique avancée'), ('hygiéniste', 'hygiéniste'), ('coordinateur', 'coordinateur')], max_length=60)),
                ('user', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('idHopital', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='DPI.hopital')),
            ],
            options={
                'db_table': 'dpi_compteinfirmier',
            },
        ),
        migrations.CreateModel(
            name='LigneAnalyse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultat', models.DecimalField(decimal_places=5, max_digits=10)),
                ('unite', models.CharField(choices=[('mm', 'mm'), ('mL', 'mL'), ('u/mL', 'u/mL'), ('mmHg', 'mmHg'), ('g/L', 'g/L'), ('mmol/mL', 'mmol/mL'), ('%', '%')], default='ml', max_length=20)),
                ('type', models.CharField(choices=[('Cholestérol', 'Cholestérol'), ('Triglycérides', 'Triglycérides'), ('Créatinine', 'Créatinine'), ('Urée', 'Urée'), ('Bilirubine', 'Bilirubine'), ('CRP', 'CRP'), ('Hématies', 'Hématies'), ('Hématocrites', 'Hématocrites'), ('Hémoglobine', 'Hémoglobine'), ('Leucocytes', 'Leucocytes'), ('Granulocytes', 'Granulocytes'), ('Thrombocytes', 'Thrombocytes'), ('GGT', 'GGT'), ('LDH', 'LDH')], default='Hémoglobine', max_length=50)),
                ('idBilanBiologique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DPI.bilanbiologique')),
            ],
            options={
                'db_table': 'dpi_ligneanalyse',
            },
        ),
        migrations.CreateModel(
            name='LigneSigneVital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultat', models.DecimalField(decimal_places=5, max_digits=10)),
                ('unite', models.CharField(choices=[('mm', 'mm'), ('mL', 'mL'), ('u/mL', 'u/mL'), ('mmHg', 'mmHg'), ('g/L', 'g/L'), ('mmol/mL', 'mmol/mL'), ('%', '%')], default='ml', max_length=20)),
                ('type', models.CharField(choices=[('Glycémie', 'Glycémie'), ('Tension artérielle systolique', 'Tension artérielle systolique'), ('Tension artérielle diastolique', 'Tension artérielle diastolique'), ('Rythme cardiaque', 'Rythme cardiaque')], default='Glycémie', max_length=50)),
                ('idBilanBiologique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DPI.bilanbiologique')),
            ],
            options={
                'db_table': 'dpi_lignesignevital',
            },
        ),
        migrations.CreateModel(
            name='EffetSecondaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptionEffetSecondaire', models.TextField(default='')),
                ('nomMedicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DPI.medicament')),
            ],
            options={
                'db_table': 'dpi_effetsecondaire',
            },
        ),
        migrations.CreateModel(
            name='Sejour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateDebutSejour', models.DateField(default=datetime.date.today)),
                ('dateFinSejour', models.DateField(default=datetime.date.today)),
                ('motifAdmission', models.TextField(default='')),
                ('idCompteMedecin', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='DPI.comptemedecin')),
                ('idDossierPatient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DPI.dpi')),
            ],
            options={
                'db_table': 'dpi_sejour',
            },
        ),
        migrations.CreateModel(
            name='Posologie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose', models.FloatField(default=1)),
                ('Frequency', models.IntegerField(default=10)),
                ('dureePrise', models.IntegerField(default=10)),
                ('nomMedicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DPI.medicament')),
                ('idSejour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DPI.sejour')),
            ],
        ),
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOrdonnance', models.DateField(default=datetime.date.today)),
                ('idSejour', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='DPI.sejour')),
            ],
            options={
                'db_table': 'dpi_ordonnance',
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateFacture', models.DateField(default=datetime.date.today)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('idSejour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DPI.sejour')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptionMaladie', models.TextField(default='')),
                ('idConsultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DPI.consultationmedicale')),
                ('idSejour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DPI.sejour')),
            ],
            options={
                'db_table': 'dpi_diagnostic',
            },
        ),
        migrations.AddField(
            model_name='consultationmedicale',
            name='idSejour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DPI.sejour'),
        ),
        migrations.CreateModel(
            name='BilanRadiologique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateExamen', models.DateField(default=datetime.date.today)),
                ('type', models.CharField(choices=[('Radiographie', 'Radiographie'), ('Echographie', 'Echographie'), ('Scanner', 'Scanner'), ('IRM', 'IRM')], default='Radiographie', max_length=20)),
                ('rapport', models.CharField(default=None, max_length=1000)),
                ('file', models.FileField(blank=True, null=True, upload_to='Attached-files/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'png', 'jpeg', 'jpg'])])),
                ('idSejour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DPI.sejour')),
            ],
            options={
                'db_table': 'dpi_bilanradiologique',
            },
        ),
        migrations.AddField(
            model_name='bilanbiologique',
            name='idSejour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DPI.sejour'),
        ),
        migrations.CreateModel(
            name='Soin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeSoin', models.CharField(choices=[("Soin d'hygiène et de confort", "Soin d'hygiène et de confort"), ('Surveillance clinique', 'Surveillance clinique'), ('Soin medical', 'Soin médical'), ('Soin spécifique', 'Soin spécifique'), ('Soin psycho-social', 'Soin psycho-social'), ("Soin d'éducation/prévention", "Soin d'éducation/prévention"), ("Soin en cas d'urgence", "Soin en cas d'urgence")], default='Soin médical', max_length=50)),
                ('resumeSoin', models.TextField(default='Fait')),
                ('idInfirmier', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='DPI.compteinfirmier')),
                ('idSejour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DPI.sejour')),
            ],
            options={
                'db_table': 'dpi_soin',
            },
        ),
        migrations.CreateModel(
            name='LigneFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fraisSoin', models.DecimalField(decimal_places=2, max_digits=10)),
                ('idFacture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DPI.facture')),
                ('idSoin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DPI.soin')),
            ],
            options={
                'db_table': 'dpi_lignefacture',
            },
        ),
    ]
