# Generated by Django 5.1.4 on 2024-12-22 19:46

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationMedicale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateConsultation', models.DateField(default=datetime.date.today)),
                ('OutilsConsultation', models.CharField(choices=[('Stéthoscope', 'Stéthoscope'), ('Tensiomètre', 'Tensiomètre'), ('Thermomètre', 'Tensiomètre')], default='Stéthoscope', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptionMaladie', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Hopital',
            fields=[
                ('nom', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('nomMedicament', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('forme', models.CharField(choices=[('Orale', 'Orale'), ('Injectable', 'Injectable'), ('Dermique', 'Dermique')], default='Orale', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CompteAdministrateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default=None, max_length=50, unique=True)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('motDePasse', models.CharField(max_length=255)),
                ('user', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompteMedecin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default=None, max_length=50, unique=True)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('motDePasse', models.CharField(max_length=255)),
                ('specialite', models.CharField(choices=[('Chirurgien', 'Chirurgien'), ('Généraliste', 'Généraliste'), ('Pédiatre', 'Pédiatre'), ('Endocrinologie', 'Endocrinologue'), ('Cardiologue', 'Cardiologue'), ('Dermatologe', 'Dermatologue'), ('Neurologe', 'Neurologue'), ('Obstétricien', 'Obstétricien'), ('Ostéologue', 'Ostéologue'), ('Ophtalmologue', 'Ophtalmologue'), ('ORL', 'ORL'), ('Gastro-entérologue', 'Gastro-entérologue'), ('Néphrologue', 'Néphrologue'), ('Anesthésiste', 'Anesthésiste')], default='Généraliste', max_length=30)),
                ('user', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('idHopital', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='DPI.hopital')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BilanRadiologique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateExamen', models.DateField(default=datetime.date.today)),
                ('resultat', models.TextField(default='')),
                ('type', models.CharField(choices=[('Radiographie', 'Radiographie'), ('Echographie', 'Echographie'), ('Scanner', 'Scanner'), ('IRM', 'IRM')], default='Radiographie', max_length=20)),
                ('rapport', models.CharField(default=None, max_length=1000)),
                ('idConsultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DPI.consultationmedicale')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BilanBiologique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateExamen', models.DateField(default=datetime.date.today)),
                ('resultat', models.TextField(default='')),
                ('resultatGlobal', models.CharField(max_length=100)),
                ('idConsultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DPI.consultationmedicale')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DPI',
            fields=[
                ('numeroSecuriteSociale', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('dateDeNaissance', models.DateField(default=datetime.date.today)),
                ('adresse', models.TextField(default='Alger')),
                ('telephone', models.DecimalField(decimal_places=0, max_digits=10)),
                ('mutuelle', models.CharField(max_length=30)),
                ('personneAcontacter', models.CharField(default=None, max_length=50)),
                ('idMedecinTraitant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='DPI.comptemedecin')),
            ],
        ),
        migrations.CreateModel(
            name='ComptePatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default=None, max_length=50, unique=True)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('motDePasse', models.CharField(max_length=255)),
                ('user', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('dossierPatient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DPI.dpi')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompteRadiologue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default=None, max_length=50, unique=True)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('motDePasse', models.CharField(max_length=255)),
                ('user', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('idHopital', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='DPI.hopital')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComptePersonnelAdministratif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default=None, max_length=50, unique=True)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('motDePasse', models.CharField(max_length=255)),
                ('service', models.CharField(choices=[('Urgences', 'Urgences'), ('Réanimation', 'Réanimation'), ('Pédiatrie', 'Pédiatrie'), ('Cardiologie', 'Cardiologie'), ('Endocrinologie', 'Endocrinologie'), ('Dermatologie', 'Dermatologie'), ('Neurologie', 'Neurologie'), ('Obstétrique', 'Obstétrique'), ('Ostéologie', 'Ostéologie'), ('Ophtalmologie', 'Ophtalmologie'), ('ORL', 'ORL'), ('Gastro-entérologie', 'Gastro-entérologie'), ('Néphrologie', 'Néphrologie'), ('Orthopédie', 'Orthopédie'), ('Anesthésiologie', 'Anesthésiologie')], default='Urgences', max_length=30)),
                ('user', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('idHopital', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='DPI.hopital')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompteLaborantin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default=None, max_length=50, unique=True)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('motDePasse', models.CharField(max_length=255)),
                ('user', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('idHopital', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='DPI.hopital')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompteInfirmier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default=None, max_length=50, unique=True)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('motDePasse', models.CharField(max_length=255)),
                ('specialite', models.CharField(choices=[('De bloc opératoire', 'De bloc opératoire'), ('Anesthésiste', 'Anesthésiste'), ('Puériculteur', 'Puériculteur'), ('En Pratique Avancée', 'En Pratique Avancée'), ('Hygiéniste', 'Hygiéniste'), ('Coordinateur', 'Coordinateur')], max_length=30)),
                ('user', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('idHopital', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='DPI.hopital')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LigneBilanBiologique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Glycémie', 'Glycémie'), ('Tension artérielle', 'Tension Artérielle'), ('Cholestérol', 'Cholestérol'), ('Triglycérides', 'Triglycérides'), ('Créatinine', 'Créatinine'), ('Urée', 'Urée'), ('Bilirubine', 'Bilirubine'), ('CRP', 'CRP'), ('Granulocytes', 'Granulocytes'), ('Thrombocytes', 'Thrombocytes')], default='Glycémie', max_length=20)),
                ('resultat', models.DecimalField(decimal_places=5, max_digits=10)),
                ('unite', models.CharField(choices=[('mm', 'mm'), ('ml', 'ml'), ('u/ml', 'u/ml')], default='ml', max_length=20)),
                ('idBilanBiologique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DPI.bilanbiologique')),
            ],
        ),
        migrations.CreateModel(
            name='EffetSecondaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptionEffetSecondaire', models.TextField(default='')),
                ('nomMedicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DPI.medicament')),
            ],
        ),
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOrdonnance', models.DateField(default=datetime.date.today)),
                ('idDiagnostic', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='DPI.diagnostic')),
            ],
        ),
        migrations.CreateModel(
            name='Posologie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose', models.FloatField(default=1)),
                ('dureePrise', models.IntegerField(default=10)),
                ('idOrdonnance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DPI.ordonnance')),
                ('nomMedicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DPI.medicament')),
            ],
        ),
        migrations.CreateModel(
            name='Sejour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateDebutSejour', models.DateField(default=datetime.date.today)),
                ('dateFinSejour', models.DateField(default=datetime.date.today)),
                ('motifAdmission', models.TextField(default='Maladie')),
                ('idCompteMedecin', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='DPI.comptemedecin')),
                ('idDossierPatient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DPI.dpi')),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateFacture', models.DateField(default=datetime.date.today)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('idSejour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DPI.sejour')),
            ],
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='idSejour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DPI.sejour'),
        ),
        migrations.AddField(
            model_name='consultationmedicale',
            name='idSejour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DPI.sejour'),
        ),
        migrations.CreateModel(
            name='Soin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeSoin', models.CharField(choices=[("Soin d'hygiène et de confort", "Soin d'hygiène et de confort"), ('Surveillance clinique', 'Surveillance clinique'), ('Soin medical', 'Soin médical'), ('Soin spécifique', 'Soin spécifique'), ('Soin psycho-social', 'Soin psycho-social'), ("Soin d'éducation/prévention", "Soin d'éducation/prévention"), ("Soin en cas d'urgence", "Soin en cas d'urgence")], default='Soin médical', max_length=50)),
                ('resumeSoin', models.TextField(default='Fait')),
                ('idInfirmier', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='DPI.compteinfirmier', to_field='email')),
                ('idSejour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DPI.sejour')),
            ],
        ),
        migrations.CreateModel(
            name='LigneFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fraisSoin', models.DecimalField(decimal_places=2, max_digits=10)),
                ('idFacture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DPI.facture')),
                ('idSoin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DPI.soin')),
            ],
        ),
    ]
