# Generated by Django 5.1.4 on 2024-12-21 16:41

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompteMedecin',
            fields=[
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('nomUtilisateur', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('motDePasse', models.CharField(max_length=255)),
                ('specialite', models.CharField(choices=[('Généraliste', 'Généraliste'), ('Pédiatre', 'Pédiatre'), ('Dermatologe', 'Dermatologue'), ('Neurologe', 'Neurologue'), ('Obstétricien', 'Obstétricien'), ('Ostéologue', 'Ostéologue'), ('Ophtalmologue', 'Ophtalmologue'), ('ORL', 'ORL'), ('Gastro-entérologue', 'Gastro-entérologue')], default='Généraliste', max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConsultationMedicale',
            fields=[
                ('idConsultation', models.CharField(max_length=19, primary_key=True, serialize=False)),
                ('dateConsultation', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('idDiagnostic', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('descriptionMaladie', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Hopital',
            fields=[
                ('nom', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('nomMedicament', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='DPI',
            fields=[
                ('numeroSecuriteSociale', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('dateDeNaissance', models.DateField(default=datetime.date.today)),
                ('adresse', models.TextField(default='Alger')),
                ('telephone', models.DecimalField(decimal_places=0, max_digits=10)),
                ('mutuelle', models.CharField(max_length=30)),
                ('personneAcontacter', models.CharField(default='azerty@gmail.com or 0792838288', max_length=50)),
                ('idMedecinTraitant', models.ForeignKey(default='MedecinTraitant', on_delete=django.db.models.deletion.DO_NOTHING, to='DPI.comptemedecin')),
            ],
        ),
        migrations.CreateModel(
            name='ComptePatient',
            fields=[
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('nomUtilisateur', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('motDePasse', models.CharField(max_length=255)),
                ('dossierPatient', models.ForeignKey(default='DossierPatient', on_delete=django.db.models.deletion.CASCADE, to='DPI.dpi')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExamenComplementaire',
            fields=[
                ('idBilan', models.CharField(max_length=19, primary_key=True, serialize=False)),
                ('dateExamen', models.DateField(default=datetime.date.today)),
                ('resultat', models.TextField(default='')),
                ('idConsultation', models.ForeignKey(default='Consultation', on_delete=django.db.models.deletion.CASCADE, to='DPI.consultationmedicale')),
            ],
        ),
        migrations.CreateModel(
            name='ComptePersonnelAdministratif',
            fields=[
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('nomUtilisateur', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('motDePasse', models.CharField(max_length=255)),
                ('service', models.CharField(choices=[('Urgences', 'Urgences'), ('Pédiatrie', 'Pédiatrie'), ('Dermatologie', 'Dermatologie'), ('Neurologie', 'Neurologie'), ('Obstétrique', 'Obstétrique'), ('Ostéologie', 'Ostéologie'), ('Ophtalmologie', 'Ophtalmologie'), ('ORL', 'ORL'), ('Gastro-entérologie', 'Gastro-entérologie')], default='Urgences', max_length=30)),
                ('idHopital', models.ForeignKey(default='Hopital', on_delete=django.db.models.deletion.CASCADE, to='DPI.hopital')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='comptemedecin',
            name='idHopital',
            field=models.ForeignKey(default='Hopital', on_delete=django.db.models.deletion.CASCADE, to='DPI.hopital'),
        ),
        migrations.CreateModel(
            name='CompteInfirmier',
            fields=[
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('nomUtilisateur', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('motDePasse', models.CharField(max_length=255)),
                ('specialite', models.CharField(choices=[('Aide soignant', 'Aide soignant'), ('Sage femme', 'Sage femme')], max_length=30)),
                ('idHopital', models.ForeignKey(default='Hopital', on_delete=django.db.models.deletion.CASCADE, to='DPI.hopital')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompteAdministrateur',
            fields=[
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('nomUtilisateur', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('motDePasse', models.CharField(max_length=255)),
                ('mdpHopital', models.CharField(max_length=50)),
                ('idHopital', models.ForeignKey(default='Hopital', on_delete=django.db.models.deletion.CASCADE, to='DPI.hopital')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EffetSecondaire',
            fields=[
                ('idEffetSecondaire', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('descriptionEffetSecondaire', models.TextField(default='')),
                ('nomMedicament', models.ForeignKey(default='Medicament', on_delete=django.db.models.deletion.CASCADE, to='DPI.medicament')),
            ],
        ),
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('idOrdonnance', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('dateOrdonnance', models.DateField(default=datetime.date.today)),
                ('idDiagnostic', models.ForeignKey(default='Diagnostic', on_delete=django.db.models.deletion.DO_NOTHING, to='DPI.diagnostic')),
            ],
        ),
        migrations.CreateModel(
            name='Posologie',
            fields=[
                ('idPosologie', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('dose', models.FloatField(default=1)),
                ('dureePrise', models.IntegerField(default=10)),
                ('idOrdonnance', models.ForeignKey(default='Ordonnance', on_delete=django.db.models.deletion.CASCADE, to='DPI.ordonnance')),
                ('nomMedicament', models.ForeignKey(default='Medicament', on_delete=django.db.models.deletion.CASCADE, to='DPI.medicament')),
            ],
        ),
        migrations.CreateModel(
            name='Sejour',
            fields=[
                ('idSejour', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('dateDebutSejour', models.DateField(default=datetime.date.today)),
                ('dateFinSejour', models.DateField(default=datetime.date.today)),
                ('motifAdmission', models.TextField(default='Maladie')),
                ('idCompteMedecin', models.ForeignKey(default='CompteMedecin', on_delete=django.db.models.deletion.DO_NOTHING, to='DPI.comptemedecin')),
                ('idDossierPatient', models.ForeignKey(default='DossierPatient', on_delete=django.db.models.deletion.CASCADE, to='DPI.dpi')),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('idFacture', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('dateFacture', models.DateField(default=datetime.date.today)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('idSejour', models.ForeignKey(default='Sejour', on_delete=django.db.models.deletion.CASCADE, to='DPI.sejour')),
            ],
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='idSejour',
            field=models.ForeignKey(default='Sejour', on_delete=django.db.models.deletion.CASCADE, to='DPI.sejour'),
        ),
        migrations.AddField(
            model_name='consultationmedicale',
            name='idSejour',
            field=models.ForeignKey(default='Sejour', on_delete=django.db.models.deletion.CASCADE, to='DPI.sejour'),
        ),
        migrations.CreateModel(
            name='Soin',
            fields=[
                ('idSoin', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('typeSoin', models.CharField(choices=[("Soin d'hygiène et de confort", "Soin d'hygiène et de confort"), ('Surveillance clinique', 'Surveillance clinique'), ('Soin medical', 'Soin médical'), ('Soin spécifique', 'Soin spécifique'), ('Soin psycho-social', 'Soin psycho-social'), ("Soin d'éducation/prévention", "Soin d'éducation/prévention"), ("Soin en cas d'urgence", "Soin en cas d'urgence")], default='Soin medical', max_length=50)),
                ('resumeSoin', models.TextField(default='Fait')),
                ('idInfirmier', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='DPI.compteinfirmier')),
                ('idSejour', models.ForeignKey(default='Soin', on_delete=django.db.models.deletion.CASCADE, to='DPI.sejour')),
            ],
        ),
        migrations.CreateModel(
            name='LigneFacture',
            fields=[
                ('idLigneFacture', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('fraisSoin', models.DecimalField(decimal_places=2, max_digits=10)),
                ('idFacture', models.ForeignKey(default='Facture', on_delete=django.db.models.deletion.CASCADE, to='DPI.facture')),
                ('idSoin', models.ForeignKey(default='Soin', on_delete=django.db.models.deletion.CASCADE, to='DPI.soin')),
            ],
        ),
    ]
