# Generated by Django 5.1.4 on 2024-12-25 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Antecedent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TypeAntecedent', models.CharField(choices=[('Médical personnel', 'Médical personnel'), ('Familial', 'Familial'), ('Médicamenteux', 'Médicamenteux'), ('Social et environnemental', 'Social et environnemental'), ('Obstétrical et gynécologique', 'Obstétrical et gynécologique')], default='Médical personnel', max_length=50)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
    ]
