# Generated by Django 5.1.4 on 2024-12-21 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compteinfirmier',
            name='specialite',
            field=models.CharField(choices=[('Aide Soignant', 'Image'), ('Sage femme', 'Video')], max_length=30),
        ),
    ]
