# Generated by Django 5.1.4 on 2024-12-22 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bilanbiologique',
            name='resultat',
        ),
        migrations.RemoveField(
            model_name='bilanradiologique',
            name='resultat',
        ),
    ]
