# Generated by Django 5.1.4 on 2024-12-22 20:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DPI', '0002_remove_bilanbiologique_resultat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PieceJointe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='Files/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'png', 'jpeg', 'jpg'])])),
            ],
        ),
    ]
