# Generated by Django 5.1.4 on 2024-12-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DPI', '0003_alter_compteinfirmier_specialite'),
    ]

    operations = [
        migrations.AddField(
            model_name='comptemedecin',
            name='specialite',
            field=models.CharField(choices=[('Généraliste', 'Generaliste'), ('Pédiatre', 'Pediatre'), ('Dermatologue', 'Dermatologue'), ('Neurologue', 'Neurologue'), ('Obstétricien', 'Obstetricien'), ('Ostéologue', 'Osteologue'), ('Ophtalmologue', 'Ophtalmologue'), ('ORL', 'Orl'), ('Gastro-entérologue', 'Gastroenterologue')], default='Généraliste', max_length=30),
        ),
        migrations.AddField(
            model_name='comptepersonneladministratif',
            name='service',
            field=models.CharField(choices=[('Urgences', 'Urgences'), ('Pédiatrie', 'Pediatrie'), ('Dermatologue', 'Dermatologie'), ('Neurologue', 'Neurologie'), ('Obstétrique', 'Obstetrique'), ('Ostéologie', 'Osteologie'), ('Ophtalmologie', 'Ophtalmologie'), ('ORL', 'Orl'), ('Gastro-entérologie', 'Gastroenterologie')], default='Urgences', max_length=30),
        ),
    ]
