# Generated by Django 5.1.4 on 2024-12-22 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DPI', '0003_piecejointe'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='medicament',
            name='quantiteStock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ComptePharmacien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default=None, max_length=50, unique=True)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('motDePasse', models.CharField(max_length=255)),
                ('idHopital', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='DPI.hopital')),
                ('user', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
