# Generated by Django 5.1.4 on 2024-12-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DPI', '0004_comptemedecin_specialite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compteadministrateur',
            name='mdpHopital',
            field=models.CharField(max_length=50),
        ),
    ]
