# Generated by Django 5.1.4 on 2024-12-31 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='antecedent',
            name='idConsultation',
        ),
        migrations.RemoveField(
            model_name='posologie',
            name='idOrdonnance',
        ),
        migrations.AddField(
            model_name='posologie',
            name='Frequency',
            field=models.IntegerField(default=10),
        ),
    ]
