# Generated by Django 5.1.4 on 2024-12-31 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DPI', '0002_remove_antecedent_idconsultation_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConsultationMedicale',
        ),
    ]
