# Generated by Django 5.1.4 on 2024-12-31 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DPI', '0003_delete_consultationmedicale'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BilanRadiologique',
        ),
    ]
