# Generated by Django 5.1.4 on 2024-12-31 23:12

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DPI', '0004_delete_bilanradiologique'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationMedicale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premiere', models.BooleanField(default=True)),
                ('dateConsultation', models.DateField(default=datetime.date.today)),
                ('outilsConsultation', models.CharField(choices=[('Stéthoscope', 'Stéthoscope'), ('Tensiomètre', 'Tensiomètre'), ('Thermomètre', 'Tensiomètre')], default='Stéthoscope', max_length=50)),
                ('resume', models.CharField(max_length=500)),
                ('idSejour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DPI.sejour')),
            ],
            options={
                'db_table': 'dpi_consultationmedicale',
            },
        ),
    ]
