# Generated by Django 5.1.4 on 2025-01-01 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DPI', '0006_bilanradiologique'),
    ]

    operations = [
        migrations.AddField(
            model_name='posologie',
            name='idSejour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DPI.sejour'),
        ),
    ]
