# Generated by Django 5.1.4 on 2025-01-03 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DPI', '0007_posologie_idsejour'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationmedicale',
            name='dateProchaineConsultation',
            field=models.DateField(blank=True, null=True),
        ),
    ]
