# Generated by Django 5.1.4 on 2025-01-01 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DPI', '0007_alter_posologie_idsejour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posologie',
            name='idSejour',
        ),
    ]
