# Generated by Django 5.1.4 on 2025-01-04 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DPI', '0006_posologie_idsejour_bilanradiologique'),
        ('DPI', '0008_consultationmedicale_dateprochaineconsultation'),
    ]

    operations = [
    ]
