# Generated by Django 5.1.4 on 2025-01-04 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DPI', '0009_merge_20250104_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='antecedent',
            name='idConsultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DPI.consultationmedicale'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='idConsultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DPI.consultationmedicale'),
        ),
        migrations.AlterField(
            model_name='posologie',
            name='idSejour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DPI.sejour'),
        ),
    ]
