# Generated by Django 5.1.4 on 2025-01-04 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posologie',
            name='idOrdonnance',
        ),
        migrations.AddField(
            model_name='consultationmedicale',
            name='dateProchaineConsultation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='idConsultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DPI.consultationmedicale'),
        ),
        migrations.AddField(
            model_name='posologie',
            name='Frequency',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='posologie',
            name='idSejour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DPI.sejour'),
        ),
        migrations.AlterField(
            model_name='antecedent',
            name='idConsultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DPI.consultationmedicale'),
        ),
    ]
