from .accounts import *
from .consultation import *
from .contact import *
from .hopital import *
from .laboratoire import *
from .login import *
from .medications import *
from .patients import *
from .sejour import *
from .facture import *
from .services import *