# Generated by Django 5.1.4 on 2024-12-19 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationMedicale',
            fields=[
                ('idConsultation', models.CharField(max_length=19, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('idDiagnostic', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='DPI',
            fields=[
                ('idDossierPatient', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('numeroSecuriteSociale', models.IntegerField(max_length=13)),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=60)),
                ('telephone', models.IntegerField(max_length=10)),
                ('mutuelle', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='EffetSecondaire',
            fields=[
                ('idEffetSecondaire', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ExamenComplementaire',
            fields=[
                ('idBilan', models.CharField(max_length=19, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('idFacture', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='LigneFacture',
            fields=[
                ('idLigneFacture', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('fraisSoin', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('nomMedicament', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('idOrdonnance', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Posologie',
            fields=[
                ('idPosologie', models.CharField(max_length=25, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sejour',
            fields=[
                ('idSejour', models.CharField(max_length=13, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Soin',
            fields=[
                ('idSoin', models.CharField(max_length=18, primary_key=True, serialize=False)),
            ],
        ),
    ]
