# Generated by Django 5.1.4 on 2024-12-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dpi',
            name='numeroSecuriteSociale',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='dpi',
            name='telephone',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
