# Generated by Django 5.1.4 on 2024-12-19 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DPI', '0002_alter_dpi_numerosecuritesociale_alter_dpi_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicament',
            name='nomMedicament',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
